#!/usr/bin/env python3
"""Check the exact player resources against reviewed and generated inputs.

This is an artifact gate, not a claim that a string search proves copyright
clearance. Public export must name only the checked plugin roots.
"""

import argparse
import ast
import hashlib
import json
from pathlib import Path


RETAINED = {
    "allegro5.cfg",
    "base_config/zc.cfg",
    "themes/mooshmood.ztheme",
    "ProggyVector-Regular.ttf",
    "assets/zc/ZC_Logo.png",
    "assets/zc/ZC_Icon_Medium_Player.png",
    "assets/zc/ZC_Forever_HD.mp3",
    "assets/zc/LICENSE.txt",
    "assets/zc/CREDITS.txt",
    "PUBLIC-CHANGES.txt",
}
REQUIRED_GENERATED = {
    "sfx.dat",
    "modules/classic/classic_fonts.dat",
    "assets/cursor.bmp",
    "assets/gui_pal.bmp",
    "assets/dungeon.mid",
    "assets/ending.mid",
    "assets/gameover.mid",
    "assets/level9.mid",
    "assets/overworld.mid",
    "assets/title.mid",
    "assets/triforce.mid",
}


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def check(package: Path, engine: Path, assets: Path, source: Path) -> None:
    manifest = json.loads((package / "manifest.json").read_text())
    assert manifest["publisher"] == {"namespace": "@simonwjackson"}
    launcher = Path(manifest["files"]["zplayer"])
    variables = {
        node.targets[0].id: ast.literal_eval(node.value)
        for node in ast.parse(launcher.read_text()).body
        if isinstance(node, ast.Assign)
        and isinstance(node.targets[0], ast.Name)
        and node.targets[0].id == "ENGINE"
    }
    assert variables["ENGINE"] == str(engine / "bin/zplayer")
    resources = engine / "share/zquestclassic"
    generated = {str(p.relative_to(assets)) for p in assets.rglob("*") if p.is_file()}
    assert REQUIRED_GENERATED <= generated, REQUIRED_GENERATED - generated
    actual = {
        str(p.relative_to(resources)) for p in resources.rglob("*") if p.is_file()
    }
    # Upstream's packager adds notices and textual changelogs, not media.
    expected = RETAINED | generated
    extra = {
        p for p in actual - expected if not p.startswith(("licenses/", "changelogs/"))
    }
    assert not extra, f"Unreviewed runtime resources: {sorted(extra)}"
    assert expected <= actual, (
        f"Missing approved resources: {sorted(expected - actual)}"
    )
    for relative in generated:
        assert digest(resources / relative) == digest(assets / relative), relative
    for relative in actual:
        assert Path(relative).suffix.lower() not in {".qst", ".nsf", ".sub"}, relative
        assert not (resources / relative).is_symlink(), relative
        if relative.startswith(("licenses/", "changelogs/")):
            # License/changelog exceptions admit text, not hidden media blobs.
            data = (resources / relative).read_bytes()
            assert b"\0" not in data, relative
            data.decode("utf-8")
    for relative in (
        "licenses/zquest_classic.LICENSE.txt",
        "licenses/zquest_classic.AUTHORS.txt",
        "licenses/pinned-dependencies/stduuid.txt",
        "licenses/pinned-dependencies/allegro5.txt",
        "licenses/pinned-dependencies/gme.txt",
        "licenses/pinned-dependencies/gme-gpl2.txt",
        "licenses/pinned-dependencies/poolSTL-Boost.txt",
        "licenses/pinned-dependencies/poolSTL-BSD.txt",
        "licenses/pinned-dependencies/poolSTL-MIT.txt",
    ):
        assert (resources / relative).stat().st_size > 50, relative
    # The exact cleaned build source must contain the resources in the output.
    # Config preprocess directives are intentionally resolved during packaging.
    for relative in RETAINED:
        if relative.endswith(".cfg"):
            continue
        assert digest(resources / relative) == digest(
            source / "resources" / relative
        ), relative
    for forbidden in ("resources-extra", "timidity", "tests", "docs-www", "icons"):
        assert not (source / forbidden).exists(), forbidden
    for path in (source / "resources").rglob("*"):
        assert path.suffix.lower() not in {".qst", ".nsf", ".sub"}, path
    # Check for the exact removed built-in presentation, not words used as API
    # identifiers, historical attribution or compatible quest type names.
    binary = (engine / "bin/zplayer").read_bytes()
    for removed in (
        b"PRODUCER... H.YAMAUCHI",
        b"THE HERO OF HYRULE.",
        b"PEACE RETURNS TO HYRULE.",
    ):
        assert removed not in binary, removed
    print(
        f"Publication gate: {len(actual)} reviewed resources; generated bytes match; no bundled quests or NSF soundtracks."
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("package", "engine", "assets", "source"):
        parser.add_argument(name, type=Path)
    arguments = parser.parse_args()
    check(arguments.package, arguments.engine, arguments.assets, arguments.source)


if __name__ == "__main__":
    main()
